//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMLib.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMLibEntities : DbContext
    {
        public PMLibEntities()
            : base("name=PMLibEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BK> BK { get; set; }
        public DbSet<Book> Book { get; set; }
        public DbSet<Librarian> Librarian { get; set; }
        public DbSet<Reader> Reader { get; set; }
        public DbSet<Record> Record { get; set; }
        public DbSet<Reserve> Reserve { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<InShelfBook> InShelfBook { get; set; }
        public DbSet<LendBook> LendBook { get; set; }
    }
}
